version: '3'
services:
  app:
    image: prakashaswathy93/task:1.0
    container_name: task
    ports:
      - "80:5000"
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/app/uploads
    depends_on:
      - db
  db:
    image: prakashaswathy93/task_db:1.0
    container_name: db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root@123"
    volumes:
      - ./task-data:/var/lib/mysql