version: '3'
services:
  app:
    image: prakashaswathy93/task:5.0
    container_name: task
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./uploads:/usr/app/uploads
    depends_on:
      - db
  db:
    image: prakashaswathy93/task_db:4.0
    container_name: db
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      HOST: "host.docker.internal"
      MYSQL_ROOT_PASSWORD: "root@123"
